#TODO Maybe missing stuff
[source]
git = "https://gitlab.redox-os.org/redox-os/freepats.git"
[build]
template = "custom"
script = """
   mkdir -pv "$1/share/freepats"
    cp -Rv ./* "$1/share/freepats"
    mkdir -pv "$1/etc/timidity"
    echo "dir /share/freepats" > "$1/etc/timidity/freepats.cfg"
    echo "source /share/freepats/freepats.cfg" >> "$1/etc/timidity/freepats.cfg"
"""