#TODO compiled but not tested
[source]
tar = "https://github.com/libsndfile/libsamplerate/releases/download/0.2.2/libsamplerate-0.2.2.tar.xz"
blake3 = "55142aae99546bd03579b8f905822cbeb72658ddd11a5c509162bcf0bf979895"
[build]
template = "configure"
