#TODO not compiled/tested
[source]
tar = "https://www.fltk.org/pub/fltk/1.3.8/fltk-1.3.8-source.tar.bz2"
[build]
template = "custom"
dependencies = [
    "mesa_glu",
    "freeglut",
    "cairo"
    "fontconfig",
    "glew",
    "libjpeg",
    "libpng",
    "pango",
    "zlib",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DOPTION_USE_CAIRO=ON
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
