#TODO compiled but not tested
[source]
tar = "https://www.fltk.org/pub/fltk/1.3.8/fltk-1.3.8-source.tar.bz2"
[build]
template = "custom"
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_CROSSCOMPILING=True
	-DCMAKE_EXE_LINKER_FLAGS="-static"
	-DCMAKE_INSTALL_PREFIX="/"
)
"""
