#TODO
[source]
tar = "https://github.com/immunant/c2rust/archive/refs/tags/v0.17.0.tar.gz"
[build]
template = "custom"
dependencies = [
    "openssl",
]
script = """
cookbook_cargo_packages c2rust
"""