#TODO missing script
[source]
tar = "https://ftp.gnome.org/pub/GNOME/sources/pango/1.42/pango-1.42.4.tar.xz"
patches = [
    "redox.patch",
]
[build]
template = "custom"
dependencies = [
    "cairo",
    "expat",
    "fontconfig",
    "freetype",
    "fribidi",
    "gettext",
    "glib",
    "harfbuzz",
    "libffi",
    "libiconv",
    "libpng",
    "pcre",
    "pixman",
    "zlib",
]