#TODO maybe wrong script
[source]
tar = "https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-1.19.tar.gz"
[build]
template = "custom"
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_CROSSCOMPILING=True
	-DCMAKE_EXE_LINKER_FLAGS="-static"
	-DCMAKE_INSTALL_PREFIX="/"
)
"""