#TODO maybe wrong
[source]
git = "https://github.com/jackpot51/pixelcannon.git"
[build]
template = "custom"
script = """
    mkdir -pv "$1/apps/pixelcannon"
    cp -Rv assets "$1/apps/pixelcannon"
    mkdir -pv "$1/ui/apps"
    cp -v manifest "$1/ui/apps/pixelcannon"
cookbook_cargo
"""
[package]
dependencies = [
    "orbital",
]