#TODO Require GTK3
[source]
git = "https://github.com/veloren/veloren"
[build]
template = "cargo"
dependencies = [
    "glib",
    "cairo",
    "pango",
    "atk",
    "gdk-pixbuf",
    "gtk3",
    "eudev",
    "mesa",
]