#TODO Compiled but not tested
[source]
git = "https://github.com/pdeljanov/Symphonia"
[build]
template = "custom"
script = """
cookbook_cargo_packages symphonia-play
mv "${COOKBOOK_STAGE}/bin/symphonia-play_symphonia-play" "${COOKBOOK_STAGE}/bin/symphonia-play"
"""
