#TODO maybe wrong
[source]
git = "https://gitlab.redox-os.org/redox-os/orbutils.git"
[build]
template = "custom"
script = """
cookbook_cargo_packages launcher
"""
[package]
dependencies = [
    "orbital"
]