[source]
git = "https://gitlab.redox-os.org/redox-os/orbutils.git"

[build]
template = "custom"
script = """
COOKBOOK_STAGE="${COOKBOOK_STAGE}/ui"
ORIGINAL_SOURCE="${COOKBOOK_SOURCE}"

COOKBOOK_SOURCE="${ORIGINAL_SOURCE}/orbutils"
cookbook_cargo

COOKBOOK_SOURCE="${ORIGINAL_SOURCE}/calculator"
cookbook_cargo
"""
