[source]
git = "https://gitlab.redox-os.org/xTibor/SpaceCadetPinball.git"
upstream = "https://github.com/k4zmu2a/SpaceCadetPinball.git"
branch = "redox"

[build]
template = "custom"
dependencies = [
    "libogg",
    "liborbital",
    "libvorbis",
    "llvm",
    "mesa",
    "sdl2",
    "sdl2_mixer",
    "zlib",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_INSTALL_PREFIX="/"
    -DSDL2_INCLUDE_DIR="${COOKBOOK_SYSROOT}/include/SDL2"
    -DSDL2_LIBRARY="-lSDL2_mixer -lvorbisfile -lvorbis -logg -lSDL2 -lorbital $("${TARGET}-pkg-config" --libs osmesa)"
    -DSDL2_MIXER_INCLUDE_DIR="${COOKBOOK_SYSROOT}/include/SDL2"
    -DSDL2_MIXER_LIBRARY="SDL2_mixer"
    "${COOKBOOK_SOURCE}"
)
set -x
cookbook_configure
mv -vT "${COOKBOOK_STAGE}"/usr/bin "${COOKBOOK_STAGE}/bin"
rmdir -v "${COOKBOOK_STAGE}"/usr
set +x
"""
