[source]
#git = "https://github.com/nghttp2/nghttp2"
#rev = "be0491294a63d891bd12b6b1b7e372a45a5d0ffe"
tar = "https://github.com/nghttp2/nghttp2/releases/download/v1.53.0/nghttp2-1.53.0.tar.xz"
blake3 = "bad5f220a66b7e6f3df20f69f4fc7e7beca46e6c143fc63b95a2656a2e897caf"
[build]
template = "custom"
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --enable-lib-only
)
cookbook_configure
"""
