[source]
git = "https://gitlab.redox-os.org/redox-os/relibc.git"

[build]
template = "custom"
script = """
rsync -av --delete "${COOKBOOK_SOURCE}/" ./
"$REDOX_MAKE" CARGO="env -u CARGO cargo" -j"$($NPROC)" DESTDIR="${COOKBOOK_STAGE}" install
"""
