#TODO make libgpg-error dependency work (after cargo update)
[source]
git = "https://github.com/cortex/ripasso"
[build]
template = "custom"
dependencies = [
    "openssl",
]
script = """
cookbook_cargo_packages ripasso-cursive
"""
