#TODO weird OpenSSL error on compilation (using cargo update)
[source]
tar = "https://github.com/Y2Z/monolith/archive/refs/tags/v2.7.0.tar.gz"
[build]
template = "cargo"
dependencies = [
    "openssl",
]
