#TODO Not compiled/tested yet
[source]
tar = "http://files.libburnia-project.org/releases/libburn-1.5.4.tar.gz"
blake3 = "50c9cfa8e92bb4faf148df6aeaaa0d02e380607714da49066d867a9d1ffcbe01"
[build]
template = "configure"