#TODO compilation error
[source]
tar = "https://ftp.gnu.org/gnu/libunistring/libunistring-1.1.tar.gz"
blake3 = "a1df9867ce4cf10d66702242549c746a14dd705612c71c987704119bd1e90a36"
[build]
template = "configure"
