#TODO Require X11/Wayland AFAIK, could be ported to orbclient (uses winit?)
[source]
tar = "https://github.com/alacritty/alacritty/archive/refs/tags/v0.12.0.tar.gz"
[build]
template = "custom"
dependencies = [
    "freetype",
    "fontconfig",
]
script = """
cookbook_cargo_packages alacritty
"""
