[source]
git = "https://github.com/RustPython/RustPython"
branch = "redox-release"

[build]
dependencies = ["openssl", "zlib"]
template = "custom"
script = """
(cd "${COOKBOOK_SOURCE}" && bash scripts/redox/uncomment-cargo.sh)
export BUILDTIME_RUSTPYTHONPATH=/lib/rustpython
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export ZLIB_STATIC=1
COOKBOOK_CARGO_FLAGS+=(--features ssl)
cookbook_cargo
mkdir -p "${COOKBOOK_STAGE}/lib"
rsync -aE \
  --exclude 'test/' \
  --exclude '__pycache__/' \
  --exclude '*.pyc' \
  --exclude '/README.md' \
  "${COOKBOOK_SOURCE}"/Lib/ "${COOKBOOK_STAGE}/lib/rustpython"
"""
