#TODO Maybe missing stuff
[source]
git = "https://gitlab.redox-os.org/redox-os/glium.git"
branch = "redox"
[build]
template = "custom"
dependencies = [
    "llvm",
    "mesa",
    "zlib",
]
script = """
cookbook_cargo_examples teapot
"""