[source]
#git = "https://gitlab.xiph.org/xiph/ogg"
#rev = "4380566a44b8d5e85ad511c9c17eb04197863ec5"
tar = "https://github.com/xiph/ogg/releases/download/v1.3.3/libogg-1.3.3.tar.xz"
blake3 = "8220c0e4082fa26c07b10bfe31f641d2e33ebe1d1bb0b20221b7016bc8b78a3a"
patches = [
    "redox.patch"
]

[build]
template = "configure"
