#TODO ring crate error (after cargo update and Redox ring fork)
[source]
tar = "https://github.com/printfn/fend/archive/refs/tags/v1.1.6.tar.gz"
[build]
template = "custom"
script = """
cookbook_cargo_packages fend
"""
