#TODO
[source]
tar = "https://github.com/neovim/neovim/archive/refs/tags/v0.9.0.tar.gz"
[build]
template = "custom"
dependencies = [
    "luajit",
    "gettext",
    "less",
    "libuv",
    "libvterm",
    "libtickit",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_CROSSCOMPILING=True
	-DCMAKE_EXE_LINKER_FLAGS="-static"
	-DCMAKE_INSTALL_PREFIX="/"
    -DENABLE_MPG123=OFF
)
"""