#TODO maybe incomplete script
[source]
git = "https://github.com/mgba-emu/mgba.git"
branch = "0.7"
patches = [
    "01_redox.patch",
]
[build]
template = "custom"
dependencies = [
    "sdl",
    "liborbital",
    "libiconv",
    "pixman",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_INSTALL_PREFIX="/"
    -DBUILD_SHARED=OFF
    -DBUILD_QT=OFF
    -DUSE_SQLITE3=OFF
    -DUSE_DEBUGGERS=OFF
    -DBUILD_SDL=ON
    -DSDL_VERSION="1.2"
    -DSDL_LIBRARY="-lSDL -lorbital"
    "${COOKBOOK_SOURCE}"
)