#TODO Not compiled/tested yet
[source]
tar = "https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.10.tar.xz"
[build]
template = "custom"
dependencies = [
    "mesa",
    "pixman",
    "gtk3",
    "openssl",
]