#TODO
[source]
tar = "https://github.com/PaddiM8/kalker/archive/refs/tags/v2.0.3.tar.gz"
[build]
template = "custom"
dependencies = [
    "libgmp",
    "mpfr",
    "mpc",
]
script = """
cookbook_cargo_packages kalker
"""
