[source]
#git = "https://git.ffmpeg.org/ffmpeg.git"
#rev = "eacfcbae690f914a4b1b4ad06999f138540cc3d8"
tar = "https://ffmpeg.org/releases/ffmpeg-5.1.2.tar.xz"
blake3 = "69fddb793c6b4fb6fd1093e54c8228c3c498614be3e48c311bb3f609a12daf5f"
patches = [
    "ffmpeg.patch"
]

[build]
template = "custom"
dependencies = [
    "liborbital",
    "llvm",
    "mesa",
    "sdl2",
    "zlib",
]
script = """
ARCH="${TARGET%%-*}"
COOKBOOK_CONFIGURE_FLAGS=(
    --enable-cross-compile
    --target-os=redox
    --arch="${ARCH}"
    --cross_prefix="${TARGET}-"
    --prefix=/
    --disable-network
    --enable-sdl2
    --enable-zlib
    --enable-encoder=png
    --enable-decoder=png
)
cookbook_configure
"""
