#TODO openssl-sys crate compilation error
[source]
tar = "https://github.com/mihaigalos/aim/archive/refs/tags/1.8.3.tar.gz"
[build]
dependencies = [
    "openssl",
]
template = "custom"
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo
"""