[source]
git = "https://gitlab.redox-os.org/redox-os/winit.git"
branch = "redox-0.27"
upstream = "https://github.com/rust-windowing/winit.git"

[build]
template = "custom"
script = """
cookbook_cargo_examples window
"""
