#TODO Not compiled/tested yet, maybe GLEW needs porting
[source]
git = "https://github.com/yvt/openspades"
[build]
template = "custom"
dependencies = [
	"glew",
	"openssl",
	"sdl2",
	"sdl2_image",
	"freealut",
	"freetype",
	"opus",
	"opusfile",
	"libjpeg",
	"openal",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
)
"""
