#TODO Needs a custom command to fetch the Irricht engine and game assets - https://github.com/minetest/minetest/blob/master/doc/compiling/linux.md
[source]
git = "https://github.com/minetest/minetest"
branch = "stable-5"
[build]
template = "custom"
dependencies = [
    "freetype",
    "sqlite",
    "zlib",
    "libpng",
    "libjpeg",
    "libogg",
    "libvorbis",
    "openal",
    "curl",
    "zstd",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
)
"""
