#TODO missing script
[source]
tar = "https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz"
patches = [
    "redox.patch",
]
[build]
template = "custom"
dependencies = [
    "sdl",
    "liborbital",
    "libogg",
    "libvorbis",
]