#TODO compiled but not tested
[source]
tar = "https://downloads.xiph.org/releases/opus/opus-1.4.tar.gz"
blake3 = "3eafe0d8609ec65d327960c062930daf324dd11de84e3b27b76db44fd0daeaac"
[build]
template = "configure"