#TODO maybe wrong template
[source]
tar = "https://download.qemu.org/qemu-3.1.0.tar.xz"
patches = [
    "redox.patch",
]
[build]
template = "configure"
dependencies = [
    "curl",
    "glib",
    "libiconv",
    "libpng",
    "pcre",
    "pixman",
    "sdl",
    "zlib",
]