#TODO Not compiled/tested yet
[source]
tar = "https://gitlab.gnome.org/GNOME/totem-pl-parser/-/archive/V_3_26_6/totem-pl-parser-V_3_26_6.tar.gz"
[build]
template = "custom"
dependencies = [
    "libxml2",
    "glib",
]