#TODO missing script
[source]
tar = "https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz"
patches = [
    "01_redox.patch",
]
[build]
template = "custom"
dependencies = [
    "sdl",
    "liborbital",
    "libiconv",
    "libjpeg",
    "libpng",
    "zlib",
]