[source]
#git = "https://git.savannah.gnu.org/git/bash.git"
#rev = "a0c0a00fc419b7bc08202a79134fcd5bc0427071"
tar = "http://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz"
blake3 = "926927c370142cffa37dfc0a310ec386493b8b558ff3cc062376898154bc7ccb"
patches = [
    "redox.patch"
]
script = """
wget -O support/config.sub "https://gitlab.redox-os.org/redox-os/gnu-config/-/raw/master/config.sub?inline=false"
"""

[build]
template = "custom"
dependencies = [
    "gettext",
    "readline",
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    ac_cv_func_wcwidth=no # TODO: add more wc functions and remove this
    bash_cv_getenv_redef=no
)
COOKBOOK_MAKE_JOBS=1 # workaround for parallel make bugs
cookbook_configure
"""
