#TODO make dependencies compile
[source]
tar = "https://ftp.gnu.org/gnu/wget/wget2-2.0.1.tar.gz"
blake3 = "d619a9fac9dab6bb907c264235952add2e2792d6beef2463bcbe92056373891a"
[build]
template = "configure"
dependencies = [
    "gettext",
    "libiconv",
    "zlib",
    "pcre",
    "gnutls",
    "bzip2",
    "xz",
    "zstd",
]
