#TODO Not compiled/tested yet, maybe enough dependencies but incomplete script
[source]
tar = "https://dl.winehq.org/wine/source/8.0/wine-8.0.1.tar.xz"
[build]
template = "configure"
dependencies = [
    "dbus",
    "fontconfig",
    "freetype",
    "gnutls",
    "libunwind",
    "gstreamer",
    "sdl2",
    "eudev",
]