#TODO Not compiled/tested yet, maybe wrong script
[source]
tar = "https://gitlab.com/xonotic/xonotic/-/archive/xonotic-v0.8.5/xonotic-xonotic-v0.8.5.tar.gz"
[build]
template = "custom"
dependencies = [
    "libgmp",
    "sdl2",
    "libjpeg",
    "libpng",
    "freetype",
    "libogg",
    "libvorbis",
    "curl",
    "rsync",
]
script = """
make
"""