#TODO compilation error
[source]
tar = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz"
[build]
template = "configure"
dependencies = [
    "openssl",
    "zlib",
    "libyaml",
    "libffi",
]