#TODO Not compiled/tested yet
[source]
tar = "https://taglib.org/releases/taglib-1.13.tar.gz"
[build]
template = "custom"
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_CROSSCOMPILING=True
	-DCMAKE_EXE_LINKER_FLAGS="-static"
	-DCMAKE_INSTALL_PREFIX="/"
)
"""