#TODO nonsense rustc version requirement
[source]
tar = "https://github.com/charliermarsh/ruff/archive/refs/tags/v0.0.270.tar.gz"
[build]
template = "custom"
script = """
cookbook_cargo_packages ruff
"""
