#TODO compilation error
[source]
tar = "https://portland.freedesktop.org/download/xdg-utils-1.1.3.tar.gz"
blake3 = "151cdbcf9dc28df1d36b866bbc028088c27d3f5fb5aea77b65d51c77f23e987e"
[build]
template = "configure"
