[source]
git = "https://gitlab.redox-os.org/redox-os/orbterm.git"

[build]
template = "custom"
script = """
COOKBOOK_STAGE="${COOKBOOK_STAGE}/ui"
cookbook_cargo
"""

[package]
dependencies = [
    "orbital"
]
