#TODO Maybe missing stuff
[source]
git = "https://gitlab.redox-os.org/redox-os/generaluser-gs.git"
[build]
template = "custom"
script = """
    mkdir -pv "$1/share/generaluser-gs"
    cp -Rv ./* "$1/share/generaluser-gs"
"""