[source]
tar = "https://github.com/Byron/gitoxide/archive/refs/tags/v0.25.0.tar.gz"
[build]
dependencies = [
    "openssl",
]
template = "custom"
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo
"""

